#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/Board.Host.Api/Board.Host.Api.csproj", "src/Board.Host.Api/"]
COPY ["src/Board.Application.AppData/Board.Application.AppData.csproj", "src/Board.Application.AppData/"]
COPY ["src/Board.Contracts/Board.Contracts.csproj", "src/Board.Contracts/"]
RUN dotnet restore "./src/Board.Host.Api/Board.Host.Api.csproj"
COPY . .
WORKDIR "/src/src/Board.Host.Api"
RUN dotnet build "./Board.Host.Api.csproj" -c %BUILD_CONFIGURATION% -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Board.Host.Api.csproj" -c %BUILD_CONFIGURATION% -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Board.Host.Api.dll"]